site_name: Citrix Director 7.16 Monitor API Reference     
site_description:  Citrix Director 7.16 Monitor API Reference
theme_dir: citrix-sdk
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      anchorlink: True

pages:
- Monitor API: index.md
- API reference:
  - Monitor.Model: api-reference/Monitor.Model.md
  - Monitor.Notifications: api-reference/Monitor.Notifications.md
